-- ============================================================================
-- 01_SCHEMA.SQL: Staging, Normalized 3NF Schema, Junctions & Audit Structures
-- ============================================================================

-- Drop existing tables (child-first)
BEGIN
    FOR t IN (
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN (
            'TITLE_DIRECTORS', 'TITLE_ACTORS', 'TITLE_GENRES', 'TITLE_COUNTRIES',
            'TITLES', 'TYPES', 'DIRECTORS', 'ACTORS', 'GENRES', 'COUNTRIES',
            'NETFLIX_STAGING', 'TITLES_AUDIT_LOG', 'ETL_ERROR_LOG'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- 1. Raw Staging Table
-- ----------------------------------------------------------------------------
CREATE TABLE netflix_staging (
    show_id       VARCHAR2(20),
    type          VARCHAR2(50),
    title         VARCHAR2(500),
    director      VARCHAR2(1000),
    cast          VARCHAR2(2000),
    country       VARCHAR2(500),
    date_added    VARCHAR2(50),
    release_year  VARCHAR2(10),
    rating        VARCHAR2(20),
    duration      VARCHAR2(50),
    listed_in     VARCHAR2(500),
    description   VARCHAR2(4000),
    loaded_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ----------------------------------------------------------------------------
-- 2. Master Lookup Tables
-- ----------------------------------------------------------------------------
CREATE TABLE types (
    type_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_name   VARCHAR2(30) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_types PRIMARY KEY (type_id),
    CONSTRAINT uq_types_name UNIQUE (type_name)
);

CREATE TABLE directors (
    director_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    director_name VARCHAR2(150) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_directors PRIMARY KEY (director_id),
    CONSTRAINT uq_directors_name UNIQUE (director_name)
);

CREATE TABLE actors (
    actor_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    actor_name  VARCHAR2(150) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_actors PRIMARY KEY (actor_id),
    CONSTRAINT uq_actors_name UNIQUE (actor_name)
);

CREATE TABLE genres (
    genre_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    genre_name  VARCHAR2(100) NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (genre_id),
    CONSTRAINT uq_genres_name UNIQUE (genre_name)
);

CREATE TABLE countries (
    country_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    country_name  VARCHAR2(100) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (country_id),
    CONSTRAINT uq_countries_name UNIQUE (country_name)
);

-- ----------------------------------------------------------------------------
-- 3. Core Entity: Titles
-- ----------------------------------------------------------------------------
CREATE TABLE titles (
    title_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    show_id          VARCHAR2(20)   NOT NULL,
    type_id          NUMBER         NOT NULL,
    title            VARCHAR2(500)  NOT NULL,
    date_added       DATE,
    release_year     NUMBER(4)      NOT NULL,
    rating           VARCHAR2(20),
    duration_value   NUMBER(5),
    duration_unit    VARCHAR2(20),
    description      VARCHAR2(4000),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_titles PRIMARY KEY (title_id),
    CONSTRAINT uq_titles_show_id UNIQUE (show_id),
    CONSTRAINT fk_titles_type FOREIGN KEY (type_id) REFERENCES types(type_id),
    CONSTRAINT chk_titles_release_year CHECK (release_year BETWEEN 1900 AND 2100),
    CONSTRAINT chk_titles_duration_unit CHECK (duration_unit IN ('min', 'Season', 'Seasons') OR duration_unit IS NULL)
);

CREATE INDEX idx_titles_date_added   ON titles(date_added);
CREATE INDEX idx_titles_release_year ON titles(release_year);
CREATE INDEX idx_titles_rating       ON titles(rating);

-- ----------------------------------------------------------------------------
-- 4. Associative / Junction Tables (Normalized 3NF)
-- ----------------------------------------------------------------------------
CREATE TABLE title_directors (
    title_id     NUMBER NOT NULL,
    director_id  NUMBER NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_title_directors PRIMARY KEY (title_id, director_id),
    CONSTRAINT fk_td_title FOREIGN KEY (title_id) REFERENCES titles(title_id) ON DELETE CASCADE,
    CONSTRAINT fk_td_director FOREIGN KEY (director_id) REFERENCES directors(director_id) ON DELETE CASCADE
);
CREATE INDEX idx_td_director ON title_directors(director_id);

CREATE TABLE title_actors (
    title_id    NUMBER NOT NULL,
    actor_id    NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_title_actors PRIMARY KEY (title_id, actor_id),
    CONSTRAINT fk_ta_title FOREIGN KEY (title_id) REFERENCES titles(title_id) ON DELETE CASCADE,
    CONSTRAINT fk_ta_actor FOREIGN KEY (actor_id) REFERENCES actors(actor_id) ON DELETE CASCADE
);
CREATE INDEX idx_ta_actor ON title_actors(actor_id);

CREATE TABLE title_genres (
    title_id    NUMBER NOT NULL,
    genre_id    NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_title_genres PRIMARY KEY (title_id, genre_id),
    CONSTRAINT fk_tg_title FOREIGN KEY (title_id) REFERENCES titles(title_id) ON DELETE CASCADE,
    CONSTRAINT fk_tg_genre FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);
CREATE INDEX idx_tg_genre ON title_genres(genre_id);

CREATE TABLE title_countries (
    title_id    NUMBER NOT NULL,
    country_id  NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_title_countries PRIMARY KEY (title_id, country_id),
    CONSTRAINT fk_tc_title FOREIGN KEY (title_id) REFERENCES titles(title_id) ON DELETE CASCADE,
    CONSTRAINT fk_tc_country FOREIGN KEY (country_id) REFERENCES countries(country_id) ON DELETE CASCADE
);
CREATE INDEX idx_tc_country ON title_countries(country_id);

-- ----------------------------------------------------------------------------
-- 5. Operational Auditing & Error Logging Tables
-- ----------------------------------------------------------------------------
CREATE TABLE etl_error_log (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    batch_id      VARCHAR2(64),
    module_name   VARCHAR2(100),
    source_record VARCHAR2(500),
    error_code    NUMBER,
    error_msg     VARCHAR2(4000),
    stack_trace   VARCHAR2(4000),
    logged_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_etl_error_log PRIMARY KEY (log_id)
);

CREATE TABLE titles_audit_log (
    audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title_id        NUMBER,
    show_id         VARCHAR2(20),
    action_type     VARCHAR2(10) NOT NULL, -- INSERT, UPDATE, DELETE
    changed_by      VARCHAR2(100) DEFAULT USER NOT NULL,
    changed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    old_title       VARCHAR2(500),
    new_title       VARCHAR2(500),
    old_rating      VARCHAR2(20),
    new_rating      VARCHAR2(20),
    old_duration    NUMBER(5),
    new_duration    NUMBER(5),
    CONSTRAINT pk_titles_audit_log PRIMARY KEY (audit_id)
);